### ISSUE TITLE
No module named 'tqdm' 에러 문의

### ISSUE THREAD

**Issue by doctorjang40-ui** [monologg/KoBERT-nsmc#5]
안녕하세요. 질문이 있어서 문의 드립니다.

pycharm에서 KoBert-nsmc-master 코드를 시행해보려는데,
(python version 3.6
pytorch version 1.4
transformers version 2.10.0) 

(kobert_nsmc2) D:\KoBERT-nsmc-master>python3 main.py --model_type kobert --do_train --do_eval
usage의 하기 명령문을 치면 

Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from trainer import Trainer
  File "D:\KoBERT-nsmc-master\trainer.py", line 5, in <module>
    from tqdm import tqdm, trange
ModuleNotFoundError: No module named 'tqdm'

에러가 발생되는데 혹시 에러의 원인 관련 추정가는 부분이 있는지 문의드립니다.

tqdm 은 설치가 되어 있습니다.
(kobert_nsmc2) D:\KoBERT-nsmc-master>conda install tqdm
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

감사합니다.

**Comment by doctorjang40-ui** [comment]
명령문에서 python3를 python으로 하니까 training하네요... 
좋은 코드 공유해주셔서 감사합니다.
